# Generated by Django 2.2.1 on 2019-06-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stormer', '0003_auto_20190609_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Feautured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
